---
- name: Configure database server
  hosts: tag_name_server_database
  gather_facts: yes
  vars_files:
    - group-vars/vault.yaml
    - group-vars/database-values.yaml
  roles:
    - role: geerlingguy.mysql
      become: true
  tasks:
    - name: Verify mysql is running
      shell: ps aux | grep mysql
      register: app_status
    - debug: msg={{ app_status.stdout_lines }}

- name: Configure web server
  hosts: tag_name_server_web
  gather_facts: true
  vars_files:
    - group-vars/vault.yaml
    - group-vars/all.yaml
  tasks:
    - name: Update apt and cache
      apt: update_cache=yes force_apt_get=true cache_valid_time=3600
      become: yes
    - name: Install java 17 and net-tools
      apt:
        pkg:
          - openjdk-17-jre-headless
          - net-tools
      become: yes
    - name: Copy jar file to web server
      copy:
        src: my-app.jar
        dest: /home/{{ instance_user }}/my-app.jar
    - name: Start the application with needed env vars
      command: java -jar my-app.jar
      environment:
        DB_USER: my-user
        DB_PWD: "{{ mysql_user_password }}"
        DB_SERVER: "{{ hostvars[groups['tag_name_server_database'][0]]['private_ip_address'] }}"
        DB_NAME: my-app-db
      async: 1000
      poll: 0
    - name: Verify app
      shell: ps aux | grep my-app.jar
      register: app_status
    - debug: msg={{ app_status.stdout_lines }}
