---
- name: Ensure ansible and boto3 are installed
  hosts: tag_name_server_ansible
  become: yes
  tasks:
    - name: Install ansible and boto3
      dnf:
        name: 
          - ansible-core
          - python3-boto3
        update_cache: yes

- name: Copy ansible playbook and configurations to ansible control server
  hosts: tag_name_server_ansible
  vars_files:
    - group-vars/vault.yaml
  tasks:
    - name: Copy ansible playbook
      copy:
        src: "{{ item }}"
        dest: /home/ec2-user
      with_fileglob: "*-app-servers.yaml"
    - name: Copy ansible.cfg
      copy:
        src: ansible.cfg
        dest: /home/ec2-user
    - name: Copy vars folder
      copy:
        src: group-vars
        dest: /home/ec2-user
    - name: Install geerlingguy.mysql role
      community.general.ansible_galaxy_install:
        type: role
        name: geerlingguy.mysql
        dest: /ansible/roles
    - name: Install amazon.aws collection
      community.general.ansible_galaxy_install:
        type: collection
        name: amazon.aws
    - name: Copy ssh key
      copy:
        src: "{{ private_server_key_location }}"
        dest: /home/ec2-user/.ssh
        owner: ec2-user
        group: ec2-user
        mode: '0600'
