---
- name: Deploy app on k8s
  hosts: localhost
  vars_files:
    - group-vars/vault.yaml
  tasks:
    - name: Deploy DB configmap
      kubernetes.core.k8s:
        src: ../db-configmap.yaml
        state: present
        api_version: v1
    - name: Deploy DB secret
      kubernetes.core.k8s:
        src: ../db-secret.yaml
        state: present
        api_version: v1
    - name: Deploy docker registry secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: my-registry-key
            namespace: default
          type: kubernetes.io/dockerconfigjson
          spec:
            dockerconfigjson: |
              {{
                {
                  "auths": {
                    "https://index.docker.io/v1/": {
                        "auth": (docker_username + ":" + docker_password) | b64encode
                    }
                  }
                 }
                } | to_json | b64encode
              }}
    - name: Deploy MYSQL db
      kubernetes.core.k8s:
        src: ../mysql.yaml
        state: present
        api_version: v1
    - name: Deploy java app
      kubernetes.core.k8s:
        src: ../java-app.yaml
        state: present
        api_version: v1
    - name: Deploy nginx-ingress controller
      kubernetes.core.helm:
        name: nginx-ingress
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress
    - name: Deploy java app ingress
      kubernetes.core.k8s:
        src: ../java-app-ingress.yaml
        state: present
        api_version: v1