---
- name: Deploy on k8s
  hosts: localhost
  vars_files:
    - group-vars/vault.yaml
  tasks:
    - name: Deploy nginx-ingress controller
      kubernetes.core.helm:
        state: present
        name: ingress-controller
        release_namespace: ingress
        create_namespace: true
        chart_ref: ingress-nginx/ingress-nginx
        values: 
          controller:
            publishService:
              enabled: true
    - name: Deploy MYSQL chart with 3 replicas
      kubernetes.core.helm:
        name: mysql
        release_namespace: default
        chart_ref: bitnami/mysql
        values_files:
          - ../k8s-manifests/mysql/mysql-multiple-replicas/mysql-chart-values-eks.yaml
    - name: Deploy DB configmap
      kubernetes.core.k8s:
        src: ../k8s-manifests/db-configmap.yaml
        state: present
    - name: Deploy DB secret
      kubernetes.core.k8s:
        src: ../k8s-manifests/db-secret.yaml
        state: present
    - name: Deploy docker registry secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: my-registry-key
            namespace: default
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: |
              {{
                {
                  "auths": {
                    "https://index.docker.io/v1/": {
                      "auth": (docker_username + ":" + docker_password) | b64encode
                    }
                  }
                } | to_json | b64encode
              }}
    - name: Deploy java app
      kubernetes.core.k8s:
        src: ../k8s-manifests/java-app.yaml
        state: present
    - name: Deploy java app ingress
      kubernetes.core.k8s:
        src: ../k8s-manifests/java-app-ingress.yaml
        state: present