---
- name: Attach DescribeInstances IAM role to ansible server
  hosts: localhost
  gather_facts: False
  vars_files:
    - group-vars/all.yaml
  tasks:
    - name: Create IAM role 
      amazon.aws.iam_role:
        name: AnsibleEC2ProvisioningRole
        assume_role_policy_document: |
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Action": [
                          "sts:AssumeRole"
                      ],
                      "Principal": {
                          "Service": [
                              "ec2.amazonaws.com"
                          ]
                      }
                  }
              ]
          }
        state: present

    - name: Create DescribeInstances IAM Policy
      amazon.aws.iam_managed_policy:
        policy_name: AnsibleEC2ProvisioningPolicy
        policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "ec2:CreateSubnet",
                  "ec2:DescribeSubnets",
                  "ec2:DeleteSubnet",
                  "ec2:CreateTags",
                  "ec2:DescribeTags",
                  "ec2:DescribeAddresses",
                  "ec2:AllocateAddress",
                  "ec2:ReleaseAddress",
                  "ec2:CreateNatGateway",
                  "ec2:DescribeNatGateways",
                  "ec2:DeleteNatGateway",
                  "ec2:CreateRouteTable",
                  "ec2:DescribeRouteTables",
                  "ec2:CreateRoute",
                  "ec2:AssociateRouteTable",
                  "ec2:DeleteRouteTable",
                  "ec2:ReplaceRoute",
                  "ec2:DisassociateRouteTable",
                  "ec2:RunInstances",
                  "ec2:DescribeInstances",
                  "ec2:TerminateInstances",
                  "ec2:DescribeImages",
                  "ec2:DescribeKeyPairs",
                  "ec2:DescribeSecurityGroups",
                  "ec2:DescribeNetworkInterfaces",
                  "ec2:AuthorizeSecurityGroupIngress",
                  "ec2:AuthorizeSecurityGroupEgress",
                  "ec2:RevokeSecurityGroupIngress",
                  "ec2:RevokeSecurityGroupEgress",
                  "ec2:DescribeInstanceAttribute"
                ],
                "Resource": "*"
              }
            ]
          }

        state: present

    - name: Attach Policy to Role
      command: >
        aws iam attach-role-policy 
        --role-name AnsibleEC2ProvisioningRole
        --policy-arn arn:aws:iam::075343202379:policy/AnsibleEC2ProvisioningPolicy
      environment:
        AWS_REGION: "{{ region_name }}"

    - name: Create Instance Profile
      amazon.aws.iam_instance_profile:
        name: AnsibleEC2ProvisioningProfile
        role: AnsibleEC2ProvisioningRole
        state: present
      register: profile_result
